# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# https://docs.docker.com/compose/gettingstarted

version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
